### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#1]
Elementi da mettere nel footer:

Links social:

1. facebook: https://www.facebook.com/karim.gorjux
2. twitter: https://twitter.com/kngorjux
3. linkedin: https://www.linkedin.com/in/karimgorjux/

Per le icone e' ok usare le glyph

Liberatoria cookie. Bisogna studiare un modo standard per metterla in ogni sito. (plugin?)

```
The cookie settings on this website are set to "allow cookies" to give you the best browsing experience possible. If you continue to use this website without changing your cookie settings or you click "Accept" below then you are consenting to this.```

**Comment by karimone** [comment]
Interessante modo per far mettere il cookie law: http://criticalsection.it/blog/eu-cookie-law-and-mezzanine/

**Comment by karimone** [comment]
La licenza dei contenuti penso andrebbe sia nel footer che in ogni articolo (al fondo). Questo e' il link alla licenza: https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by karimone** [comment]
Qui alcune icone per la licenza da mattere nel fotter: https://creativecommons.org/choose/results-one?license_code=by-nc-nd&amp;jurisdiction=&amp;version=4.0&amp;lang=en

**Comment by karimone** [comment]
Questa la versione italiana: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.it

**Comment by mauri1982** [comment]
dovrei aver risolto. dai un occhiata

**Comment by mauri1982** [comment]
io metterei anche un copyright, che dici?
