### ISSUE TITLE
Mancano immagini in static

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#10]
- facebook_footer.png
- twitter_footer.png
- linkedin_footer.png
- rss_footer.png

**Comment by mauri1982** [comment]
le immagini non sono state proprio caricate. 
eppure git mi dice che il branch develop non ha nulla da pushare...

mauri@DESKTOP-4GVVMPR MINGW64 /d/vagrant/karimBlog (develop)
$ git push
Everything up-to-date

**Comment by mauri1982** [comment]
non ho idea di come risolverlo... per lui è tutto pubblicato. idee?

**Comment by karimone** [comment]
Mandami i files qui.

**Comment by mauri1982** [comment]
![twitter_footer](https://cloud.githubusercontent.com/assets/22234609/26102867/a3fb7dee-3a3f-11e7-839e-bfbecc186707.png)
![twitter_footer_hover](https://cloud.githubusercontent.com/assets/22234609/26102864/a3f8e066-3a3f-11e7-9779-c9ec29b51545.png)
![baloon](https://cloud.githubusercontent.com/assets/22234609/26102863/a3f82964-3a3f-11e7-996e-42cc2068dc3b.gif)
![facebook_footer](https://cloud.githubusercontent.com/assets/22234609/26102865/a3fa2624-3a3f-11e7-8664-052b2062ecb9.png)
![facebook_footer_hover](https://cloud.githubusercontent.com/assets/22234609/26102866/a3fa2f2a-3a3f-11e7-90ee-044989fbb01e.png)
![fb](https://cloud.githubusercontent.com/assets/22234609/26102868/a4022b08-3a3f-11e7-9711-ebe7af10ebb7.png)
![like](https://cloud.githubusercontent.com/assets/22234609/26102872/a41a5f3e-3a3f-11e7-841a-cd6afa531a29.png)
![linkedin_footer](https://cloud.githubusercontent.com/assets/22234609/26102870/a4166212-3a3f-11e7-812f-d891dd2a39ff.png)
![linkedin_footer_hover](https://cloud.githubusercontent.com/assets/22234609/26102874/a41f5e4e-3a3f-11e7-9045-c7831ea14755.png)
![rss_footer](https://cloud.githubusercontent.com/assets/22234609/26102871/a4195cf6-3a3f-11e7-8610-301f7b3c2c1e.png)
![rss_footer_hover](https://cloud.githubusercontent.com/assets/22234609/26102873/a41c4326-3a3f-11e7-942d-b36272ba2ae5.png)
![tw](https://cloud.githubusercontent.com/assets/22234609/26102875/a4276288-3a3f-11e7-9190-65bf8b26b44d.png)
![twitter](https://cloud.githubusercontent.com/assets/22234609/26102876/a432ad14-3a3f-11e7-8ae5-0f7351bd9640.png)

**Comment by mauri1982** [comment]
il problema è che lui vede come pubblicate cose che non sono.
perche?
