### ISSUE TITLE
Accordion tag

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#12]
Sarebbe interessante fare un template tag che "accordizzi" un div.

Il codice per farlo, senza nemmeno scomodare jquery:
https://www.w3schools.com/howto/howto_js_accordion.asp

**Comment by mauri1982** [comment]
l'accordion è abbastanza semplice. ma non ho capito cosa vuoi accordionizzare. non ci sono sections...

**Comment by karimone** [comment]
Voglio 'accordare' gli archivi per anno.

**Comment by mauri1982** [comment]
accordion inserito. manca la grafica
