### ISSUE TITLE
Rimuovere il codice commentato dal template

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#13]
Non tenere del codice commentato nel template, non e' necessario e a lungo andare puo' creare piu' fastidio che altro. Usiamo git quindi se c'e' qualcosa che devi recuperare, puoi sempre cercare nelle versioni precedenti.

**Comment by mauri1982** [comment]
perche devo togliere i commenti?
metti ad esempio che in futuro potrebbe tornarmi utile quella cosa?

**Comment by karimone** [comment]
Se in futuro hai bisogno ti cerchi il codice nei vecchi commit o recuperi
il template originale. Se lasci tutto quello che non usi, il progetto
diventa ingestibile
-- 
Karim Norman Gorjux
Mob: +61481173913 • Skype: karimac
Linkedin: au.linkedin.com/in/karimgorjux/
Blog (italian): www.karimblog.net
