### ISSUE TITLE
Imparare l'uso del translate nei template di django

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#14]
Qui viene spiegato come vengono usati i tools di i18n sui template:
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#internationalization-in-template-code

Piu' a fondo e' spiegato come produrre le traduzioni:
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#localization-how-to-create-language-files

Non devi sapere tutto, ma cosa e' importante da sapere e' che il testo e' SEMPRE SCRITTO IN INGLESE, poi il file di traduzione prodotto mostrera' il sito in varie lingue

**Comment by mauri1982** [comment]
ma questa roba per cosa è? per il multilingua?

**Comment by karimone** [comment]
Si, ma il frontend non viene tradotto dal database. Solo i contenuti
dinamici lo sono.
-- 
Karim Norman Gorjux
Mob: +61481173913 • Skype: karimac
Linkedin: au.linkedin.com/in/karimgorjux/
Blog (italian): www.karimblog.net

**Comment by mauri1982** [comment]
e quindi io cosa dovrei fare? un template per lingua? diventa assurdo...

**Comment by karimone** [comment]
Non devi tradurre in italiano i testi che sono passati a trans.

{% trans 'Archive' %} non lo traduci modificando 'Archive. Se vuoi scrivere
direttamente in italiano allora togli 'Archive', ma se tieni il trans, il
template è riutilizzabile in qualsiasi lingua sia il sito. (Vedi docs)
-- 
Karim Norman Gorjux
Mob: +61481173913 • Skype: karimac
Linkedin: au.linkedin.com/in/karimgorjux/
Blog (italian): www.karimblog.net

**Comment by mauri1982** [comment]
devo leggermelo con calma perche c'ho capito na sega

**Comment by karimone** [comment]
Se vuoi scrivere direttamente in italiano allora togli 'Archive'

Sbagliato,

Volevo dire: Se vuoi scrivere direttamente in italiano allora togli trans e
metti direttamente puro testo in italiano.
-- 
Karim Norman Gorjux
Mob: +61481173913 • Skype: karimac
Linkedin: au.linkedin.com/in/karimgorjux/
Blog (italian): www.karimblog.net
