### ISSUE TITLE
Larghezza della pagina contattami sbagliata

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#15]
Dopo che ho cambiato l'extend la pagina contattami e' sballata.

**Comment by mauri1982** [comment]
dovrei avere risolto, ma purtroppo non posso confermare. mi da errore se carico la pagina contatti.

ailed lookup for key [form] in u"[{u'_parent_page_ids': {1: None, 2: None, 3: None, 4: None, 38: None}, 'None': None, 'False': False, u'menu_pages': defaultdict(<type 'list'>, {None: [<Page: Chi sono?>, <Page: Blog>, <Page: Contattami>, <Page: Chi sono>, <Page: Contattami>]}), u'has_home': False, u'on_home': False, u'_current_page': <Page: Contattami>, 'True': True}, {}, {}]"

controlla tu
