### ISSUE TITLE
Icone RSS/Feed

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#2]
Si trovano al fondo della sidebar. Sarebbe meglio iconizzarle con l'icona dell'RSS

**Comment by mauri1982** [comment]
mi fa cagare un icona in fondo ad un elenco. 
ho provato a spostarlo in fondo al footer..dimmi se puo funzionare. l'unica cosa è che cosi prende tutto il blog

**Comment by karimone** [comment]
no capito.
Parliamone su skype

**Comment by mauri1982** [comment]
ho inserito l'icona dell'rss nel footer. dovrebbe funzionare allo stesso modo, credo...
