### ISSUE TITLE
Post meta nel titolo

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#20]
Il rendering non e' dei migliori su telefono e penso che i commenti dovrebbero stare nella stessa linea. Idee?

![screen shot 2017-05-30 at 17 58 16](https://cloud.githubusercontent.com/assets/564180/26573612/d16ae5c6-4561-11e7-8e04-ef5c7589d550.png)

**Comment by mauri1982** [comment]
ho sistemato la riga nella home.
sinceramente io seccerei il "nessun commento" qui, non ha molto senso metterlo in testata.
