### ISSUE TITLE
Post footer: condivisione e navigazione

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#21]
Appena trovo un esempio di come vorrei le condivisioni, te le allego. Intanto bisognerebbe vedere come fare il precedente ed il successivo.

![screen shot 2017-05-30 at 17 58 57](https://cloud.githubusercontent.com/assets/564180/26573692/0d0a987e-4562-11e7-92ca-e78900c233f0.png)

**Comment by mauri1982** [comment]
sistemate categorie e next/prev. 
rimane lo sharing e il like
