### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#22]
Aggiungere una rientranza e cambiare il titolo. Gli elementi nella sidebar vengono chiamati "widget". Un div .widget-content farebbe la rientranza:

![screen shot 2017-05-30 at 17 59 12](https://cloud.githubusercontent.com/assets/564180/26573896/c4265cdc-4562-11e7-8803-293a91c2b8d1.png)
![screen shot 2017-05-30 at 17 59 02](https://cloud.githubusercontent.com/assets/564180/26573897/c44dfeb8-4562-11e7-90a8-643d8e3674ca.png)
![screen shot 2017-05-30 at 17 59 21](https://cloud.githubusercontent.com/assets/564180/26573898/c4528b40-4562-11e7-9c13-213fb00f5231.png)

Anche Archivio dovrebbe essere migliorato come spazi tra i vari anni. (Devo ancora aggiungere gli articoli per anno)

**Comment by mauri1982** [comment]
ho ridotto l'interlinea. in realta non ho ben capito cosa vorresti farci. parliamone a voce
