### ISSUE TITLE
Suggerimenti post rendering

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#23]
Ecco alcune cose che ho trovato in giro

![screen shot 2017-05-30 at 18 12 57](https://cloud.githubusercontent.com/assets/564180/26574439/b18db870-4564-11e7-9913-4358ae8c7cd5.png)
![screen shot 2017-05-30 at 18 18 00](https://cloud.githubusercontent.com/assets/564180/26574441/b1c351a6-4564-11e7-9021-ceb8eabf30af.png)
![screen shot 2017-05-30 at 18 18 16](https://cloud.githubusercontent.com/assets/564180/26574442/b21458f8-4564-11e7-9717-a966ea992a6e.png)

**Comment by mauri1982** [comment]
quanti elementi vuoi inserire? io in parte l'ho gia modificato, dai un occhiata
