### ISSUE TITLE
problema con l'header

### ISSUE THREAD

**Issue by mauri1982** [karimone/kng_site#27]
mi sono accorto di non capire come funzionano i load.
ho messo l'header in import, visto che è presente sia nel post_detail che nel list, ma il sito crasha. credo di aver saltato qualche load, ma non capisco quale.

meglio risolvere con tim viuer

**Comment by karimone** [comment]
Se crasha posta l'errore qui così almeno capisco cos'è
-- 
Karim Norman Gorjux
Mob: +61481173913 • Skype: karimac
Linkedin: au.linkedin.com/in/karimgorjux/
Blog (italian): www.karimblog.net

**Comment by mauri1982** [comment]
**blog post list** 
nel blog post list ho incluso questi load.
ma, onestamente, non ho idea di quali siano.
{% load pages_tags mezzanine_tags i18n static karimblog keyword_tags disqus_tags %}

ho incluso questo:
{% block header %}
{% include "blog/includes/header.html" %}
{% endblock header %}

**header.html**
nell'header caricata ho inserito questo codice. dubito i load siano corretti

{% load pages_tags mezzanine_tags i18n static karimblog %}
    <div class="container-fluid">
        <div class="row">
            
            <header class="col-xs-12 static_header {% get_karimblog_header %}">
                <h1>
                    <span class="sectionTitle">karim<br> </span>Blog
                </h1>
            </header>

        </div>
    </div>

**errore di mezzanine**
KeyError at /

'blog_post'

Request Method: 	GET
Request URL: 	http://192.168.56.10:8000/
Django Version: 	1.10.7
Exception Type: 	KeyError
Exception Value: 	

'blog_post'

Exception Location: 	/home/ubuntu/virtualenvs/karimblog/lib/python3.5/site-packages/django/template/context.py in __getitem__, line 75
Python Executable: 	/home/ubuntu/virtualenvs/karimblog/bin/python
Python Version: 	3.5.2
Python Path: 	

['/vagrant/karimblog',
 '/home/ubuntu/virtualenvs/karimblog/lib/python35.zip',
 '/home/ubuntu/virtualenvs/karimblog/lib/python3.5',
 '/home/ubuntu/virtualenvs/karimblog/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/ubuntu/virtualenvs/karimblog/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/ubuntu/virtualenvs/karimblog/lib/python3.5/site-packages']

**Comment by karimone** [comment]
Da qualche parte ti riferisci a 'blog_post', ma non è disponibile. Non
penso sia un problema del template. Stai usando il db giusto?
-- 
Karim Norman Gorjux
Mob: +61481173913 • Skype: karimac
Linkedin: au.linkedin.com/in/karimgorjux/
Blog (italian): www.karimblog.net

**Comment by mauri1982** [comment]
il db che ho in locale, non quelo sul tuo server
