### ISSUE TITLE
Usare il templatetag per l'header in base alla categoria

### ISSUE THREAD

**Issue by karimone** [karimone/kng_site#4]
Il templatetag e' presente e funziona, ora bisogna decidere se usarlo con JS dato che l'header e' nel CSS e django non puo' modificarlo. Altrimenti devi caricare l'header usando un `<img src="">`

**Comment by mauri1982** [comment]
risolto.
ti ho modificato il settings e il templatetags.py, avevo bisogno di una variabile non di un path
